### PR TITLE
Bump react and react-dom from 16.8.0 to 17.0.2

### LINKED ISSUE #584: upgrade React version in peer dependency to 17.
Is it possible to bump the deps version?

### PR DESCRIPTION
**Pull request by yuribit**
I've been playing with it for a couple of weeks and haven't noticed any issue.

Thanks!

Fixes #584.

### CODE REVIEW

**Comment by chuckcarpenter** [comment]
Thank you @yuribit !

**Comment by ulken** [comment]
> @chuckcarpenter would it be possible to publish this change to npm?
> 
> Can't seem to install directly from commit hash since you're using workspaces and you can't target subdirectories.

cc @rwwagner90

**Comment by ulken** [comment]
@chuckcarpenter @rwwagner90 bump. Would it at least be possible to release a new tag?

**Comment by chuckcarpenter** [comment]
@ulken Apologies for the long delay. Aside from becoming a contributor with publish permissions on the project, there was really nothing you can do. We have started to get more help on our team and hoping in the future we can do better to at least keep dependencies more updated and published.

**Comment by chuckcarpenter** [comment]
v3.3.4 was published.

**Comment by ulken** [comment]
@chuckcarpenter Thank you for getting back to me. Much appreciated. Sounds promising.

> Aside from becoming a contributor with publish permissions on the project, there was really nothing you can do.

Not entirely sure if you're holding out a hand asking for help or simply re-iterating there really wasn't much I could do. If the former, sure, I could help out, but I'm assuming you want to limit permissions to inside the company?

**Comment by chuckcarpenter** [comment]
@ulken yeah, for now I was just indicating that you'd done everything you can. Hopefully, we'll have more people inside our company who can help do releases sooner than later.

**Comment by mp27** [comment]
@chuckcarpenter @yuribit this should be a major version, why is bumping the react dependency to another major version as just a small one for this library? It introduces breaking changes on the dependency...

**Comment by chuckcarpenter** [comment]
@mp27 I believe this was due to React 17 being a stepping stone release with little to no breaking changes. Especially if you have a tree with another version of React. e.g., https://reactjs.org/blog/2020/10/20/react-v17.html

Are you having issues w/ this release or just disagree with the semver applied?

**Comment by mp27** [comment]
@chuckcarpenter both, the thing is that usually on a project there are multiple libraries that might depend on a specific major version of react, at the same time that project might be dependent on a specific major of npm and node. 

When this happens, installing packages with core dependencies that gets upgraded to a major as is something small...gets messy. Isn't the practice to have the core(react in this case) dependencies lock on a major version of your app, like v3 is with react 16, v4 with react 17, v3 getting deprecated soon etc. it would also be clearer, but this will save time for those who are on that case and do a casual minor update but that will break the application.

On my case, npm had versioning conflicts and had to lock on 3.3.3 as the easiest solution.

**Pull request merged**
