### PR TITLE
Export more types to allow consumers to reuse them

### LINKED ISSUE #418: Consider exporting more types
I'd like to declare my steps and button arrays as typed constants: 

```ts
const steps: ? = [];
const buttons: ? = [];
```

However, types like `ShepherdOptionsWithType` aren't exported:

```
Module '"../node_modules/react-shepherd/dist"' declares 'ShepherdOptionsWithType' locally, but it is not exported.
```

### PR DESCRIPTION
**Pull request by shepmaster**
Closes #418

### CODE REVIEW

**Comment by rwwagner90** [comment]
@shepmaster we shouldn't really do anything with types here. Types should come from Shepherd, not react-shepherd.

**Comment by shepmaster** [comment]
> Types should come from Shepherd,

This is mildly annoying as a user, because now I have to add two dependencies to my project (react-shepherd and Shepherd), even though my project isn't directly using Shepherd. It also means that I have to manually ensure that the two versions of Shepherd match over time and upgrades.

Additionally, some of these types *must* come from react-shepherd because that's what defines them (the enhanced interfaces).

**Comment by rwwagner90** [comment]
@shepmaster you shouldn't need two dependencies. What I mean is we should expose all the types in Shepherd, then import them for use here in react-shepherd. I know some do need to be exported here, but we should do as many things as we can in Shepherd itself. Does that make sense?

**Comment by Dvvarf** [comment]
@rwwagner90 but isn't that's exactly what this PR doing? It imports and re-exports the types from Shepherd.js and then exports some more. It doesn't add anything extra, core types are still in Shepherd.js.

Small note: I believe ShepherdProps should also be exported.

**Review by rwwagner90 — APPROVED** [review]

**Comment by rwwagner90** [comment]
@chuckcarpenter can you weigh in here? I'm fine to merge if you are, but all of CI seems to be red.

**Comment by chuckcarpenter** [comment]
@shepmaster @Dvvarf I opened a new PR brining in these changes and fixes the tests, if you want to test and review? https://github.com/shipshapecode/react-shepherd/pull/439

**Comment by rwwagner90** [comment]
Closed by #439

**Pull request closed without merging**
