### PR TITLE
Manage secondary property on Step button

### PR DESCRIPTION
**Pull request by linsolas**
Hello,

The TypeScript definition of `StepOptionsButton` in Shepherd core JS is missing the `secondary` property. I've made a [PR](https://github.com/shipshapecode/shepherd/pull/1040) to solve this issue.

One _real_ impact is that the property is ignored by `react-shepherd` library. This PR fixes that.

### CODE REVIEW

**Comment by chuckcarpenter** [comment]
@linsolas since https://github.com/shipshapecode/shepherd/pull/1040 was merged and released, do you want to update the interface here to get this one in as well?

**Comment by linsolas** [comment]
Hello @chuckcarpenter 

Thanks for the information. I didn't notice there was a new version of shepherd released.
However, I suspect I first need to wait react-shepherd to depend on v8 of shepherd (like suggested in the PR #346)...

**Comment by chuckcarpenter** [comment]
@linsolas just published v3.3.0

**Comment by linsolas** [comment]
Hello @chuckcarpenter 

I've updated my PR. I had to update the dependency on `shepherd.js` to `8.0.2` (and therefore the PR #392 becomes useless)...

**Pull request merged**
